In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
forbes2018_file = "Resources/forbes_2018.csv"
premise_df = pd.read_csv(forbes2018_file)
premise_df.head()

,position,name,lastName,age,country,gender,wealthSource,industry,worth,worthChange,realTimeWorth,realTimePosition,image
0,NaN,Anant Asavabhokhin & family,Asavabhokhin,67.0,Thailand,M,real estate,Real Estate,NaN,-0.001,NaN,1613,https://specials-images.forbesimg.com/imageser...
1,NaN,Arash Ferdowsi,Ferdowsi,32.0,United States,M,online file storage,Technology,NaN,0.000,NaN,1734,https://specials-images.forbesimg.com/imageser...
2,NaN,Banthoon Lamsam & family,Lamsam,65.0,Thailand,M,banking,Finance and Investments,NaN,0.001,NaN,1952,https://specials-images.forbesimg.com/imageser...
3,NaN,Bill Adderley & family,Adderley,70.0,United Kingdom,M,home furnishings,Fashion & Retail,NaN,0.000,NaN,1956,https://specials-images.forbesimg.com/imageser...
4,NaN,Boris Zingarevich,Zingarevich,58.0,Russia,M,"pulp and paper, diversified",Diversified,NaN,0.000,NaN,2103,https://specials-images.forbesimg.com/imageser...

In [4]:
forbes2020_largest = "Resources/forbes_top_2000_world_largest_public_companies.csv"
largest2000_df = pd.read_csv(forbes200_file )
premise2000_df.head()

,position,name,lastName,age,country,gender,wealthSource,industry,worth,worthChange,realTimeWorth,realTimePosition,image
0,NaN,Anant Asavabhokhin & family,Asavabhokhin,67.0,Thailand,M,real estate,Real Estate,NaN,-0.001,NaN,1613,https://specials-images.forbesimg.com/imageser...
1,NaN,Arash Ferdowsi,Ferdowsi,32.0,United States,M,online file storage,Technology,NaN,0.000,NaN,1734,https://specials-images.forbesimg.com/imageser...
2,NaN,Banthoon Lamsam & family,Lamsam,65.0,Thailand,M,banking,Finance and Investments,NaN,0.001,NaN,1952,https://specials-images.forbesimg.com/imageser...
3,NaN,Bill Adderley & family,Adderley,70.0,United Kingdom,M,home furnishings,Fashion & Retail,NaN,0.000,NaN,1956,https://specials-images.forbesimg.com/imageser...
4,NaN,Boris Zingarevich,Zingarevich,58.0,Russia,M,"pulp and paper, diversified",Diversified,NaN,0.000,NaN,2103,https://specials-images.forbesimg.com/imageser...